name: Compile LaTeX with Asymptote and SVG

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git Repository
        uses: actions/checkout@v4

      - name: Install LaTeX, Asymptote and Inkscape
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-science texlive-lang-cyrillic cm-super asymptote texlive-bibtex-extra biber inkscape

      - name: Compile Document
        run: |
          # Переходим в папку с исходниками
          cd src
          
          # Флаг -jobname задает имя итогового файла. Мы назвали его diploma_final
          pdflatex -interaction=nonstopmode -shell-escape -jobname=diploma_final main.tex || true
          
          asy *.asy || echo "No .asy files to compile"
          
          # ВАЖНО: biber теперь должен обрабатывать именно технический файл diploma_final, а не main
          biber diploma_final || echo "No bibliography to compile"
          
          pdflatex -interaction=nonstopmode -shell-escape -jobname=diploma_final main.tex || true
          pdflatex -interaction=nonstopmode -shell-escape -jobname=diploma_final main.tex || true
          
          # Возвращаемся в корень и копируем готовый PDF из папки src в корень репозитория
          cd ..
          cp src/diploma_final.pdf ./diploma_final.pdf

      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Добавляем в репозиторий файл, который мы скопировали в корень
          git add diploma_final.pdf
          git commit -m "Automated PDF generation (diploma_final.pdf)" || echo "No changes to commit"
          git push
